import crypto from "node:crypto";
import { readRunArtifact, writeRunArtifact } from "./artifacts.js";
import { InputError } from "./errors.js";
import { newId, nowIso } from "./ids.js";
import type {
  ExternalTransferArtifactRef,
  ExternalTransferManifest,
  ExternalTransferPurpose,
  ExternalTransferRisk,
  JsonObject,
  RoleAssignment,
  RunArtifact,
  RunRecord,
  RuntimeRole
} from "./types.js";

export interface BuildExternalTransferManifestInput {
  run: RunRecord;
  role: RuntimeRole;
  destination: RoleAssignment;
  purpose: ExternalTransferPurpose;
  approvalPhrase: string;
  artifacts: RunArtifact[];
}

export interface ExternalTransferPreview {
  manifestArtifact: RunArtifact;
  manifest: ExternalTransferManifest;
}

const maxArtifactBytes = 200_000;
const previewBytes = 4_000;

const secretPatterns = [
  /api[_-]?key/i,
  /authorization:\s*bearer/i,
  /password/i,
  /secret/i,
  /session[_-]?token/i,
  /ssh-rsa|-----BEGIN [A-Z ]*PRIVATE KEY-----/
];

const sha256 = (value: string): string =>
  crypto.createHash("sha256").update(value).digest("hex");

const artifactRiskClass = (purpose: ExternalTransferPurpose): ExternalTransferRisk["class"] => {
  switch (purpose) {
    case "progress_packet":
    case "memory_packet":
    case "reconciliation":
      return "private_runtime_memory";
    case "repo_context":
      return "repo_context";
  }
};

const detectSecretPatternHits = (content: string): number =>
  secretPatterns.filter((pattern) => pattern.test(content)).length;

const buildRisk = (
  purpose: ExternalTransferPurpose,
  artifactContents: string[]
): ExternalTransferRisk => {
  const secretPatternHits = artifactContents.reduce(
    (count, content) => count + detectSecretPatternHits(content),
    0
  );
  const reasons = [
    purpose === "repo_context"
      ? "Transfer includes runtime-captured repository context."
      : "Transfer includes private TheHood runtime memory."
  ];

  if (secretPatternHits > 0) {
    reasons.push("Secret-like text was detected in the transfer source artifact preview.");
  }

  return {
    class: secretPatternHits > 0 ? "secret_risk" : artifactRiskClass(purpose),
    reasons,
    secretPatternHits
  };
};

const artifactRef = async (
  run: RunRecord,
  artifact: RunArtifact
): Promise<{ ref: ExternalTransferArtifactRef; content: string }> => {
  const result = await readRunArtifact({
    repoPath: run.repoPath,
    runId: run.runId,
    ref: artifact.ref,
    maxBytes: maxArtifactBytes
  });

  if (result.truncated) {
    throw new InputError(`External transfer source artifact is too large to review safely: ${artifact.ref}`);
  }

  return {
    ref: {
      kind: artifact.kind,
      ref: artifact.ref,
      summary: artifact.summary,
      byteLength: result.byteLength,
      truncated: result.truncated,
      sha256: sha256(result.content)
    },
    content: result.content
  };
};

const previewContent = (contents: string[]): { content: string; truncated: boolean } => {
  const joined = contents.join("\n\n--- artifact boundary ---\n\n");
  const truncated = Buffer.byteLength(joined, "utf8") > previewBytes;

  return {
    content: joined.slice(0, previewBytes),
    truncated
  };
};

export const buildExternalTransferManifest = async (
  input: BuildExternalTransferManifestInput
): Promise<ExternalTransferManifest> => {
  const inspected = await Promise.all(input.artifacts.map((artifact) => artifactRef(input.run, artifact)));
  const contents = inspected.map((item) => item.content);
  const preview = previewContent(contents);
  const approvalHint = `I approve ${input.approvalPhrase} for run ${input.run.runId}.`;

  return {
    schemaVersion: 1,
    kind: "external_transfer_manifest",
    runId: input.run.runId,
    createdAt: nowIso(),
    destination: input.destination,
    role: input.role,
    purpose: input.purpose,
    approvalPhrase: input.approvalPhrase,
    approvalHint,
    artifacts: inspected.map((item) => item.ref),
    totalBytes: inspected.reduce((total, item) => total + item.ref.byteLength, 0),
    risk: buildRisk(input.purpose, contents),
    redaction: {
      status: "not_applied",
      notes: [
        "The manifest previews the exact bounded artifact content before external transfer.",
        "Source artifacts remain canonical; provider-visible packets are built from these artifacts."
      ]
    },
    preview: {
      maxBytes: previewBytes,
      content: preview.content,
      truncated: preview.truncated
    },
    provenance: {
      sourceArtifactRefs: input.artifacts.map((artifact) => artifact.ref),
      notes: [
        "Generated by the runtime before an external provider transfer approval gate.",
        "Approval should be based on this manifest, not on provider session context."
      ]
    }
  };
};

export const writeExternalTransferManifestArtifact = async (
  input: BuildExternalTransferManifestInput
): Promise<{ manifest: ExternalTransferManifest; artifact: RunArtifact }> => {
  const manifest = await buildExternalTransferManifest(input);
  const artifact = await writeRunArtifact({
    repoPath: input.run.repoPath,
    runId: input.run.runId,
    kind: "transfer_manifest",
    name: `${input.purpose}-${input.destination.provider}-${newId("transfer")}.json`,
    content: `${JSON.stringify(manifest, null, 2)}\n`,
    summary: `${input.purpose} transfer manifest for ${input.destination.provider}:${input.destination.model}.`
  });

  return {
    manifest,
    artifact
  };
};

const isManifest = (value: unknown): value is ExternalTransferManifest =>
  value !== null &&
  typeof value === "object" &&
  !Array.isArray(value) &&
  (value as { kind?: unknown }).kind === "external_transfer_manifest";

export const readLatestExternalTransferManifest = async (
  run: RunRecord
): Promise<ExternalTransferPreview> => {
  const manifestArtifact = run.artifacts.filter((artifact) => artifact.kind === "transfer_manifest").at(-1);

  if (!manifestArtifact) {
    throw new InputError(`Run ${run.runId} does not have a transfer manifest artifact.`);
  }

  const result = await readRunArtifact({
    repoPath: run.repoPath,
    runId: run.runId,
    ref: manifestArtifact.ref,
    maxBytes: maxArtifactBytes
  });
  const parsed = JSON.parse(result.content) as unknown;

  if (!isManifest(parsed)) {
    throw new InputError(`Transfer manifest artifact is invalid: ${manifestArtifact.ref}`);
  }

  return {
    manifestArtifact,
    manifest: parsed
  };
};

export const transferManifestSummary = (manifest: ExternalTransferManifest): JsonObject => ({
  destination: `${manifest.destination.provider}:${manifest.destination.model}`,
  purpose: manifest.purpose,
  riskClass: manifest.risk.class,
  totalBytes: manifest.totalBytes,
  artifactCount: manifest.artifacts.length,
  approvalPhrase: manifest.approvalPhrase
});
